<?xml version="1.0" encoding="UTF-8"?>
<testng-results total="3" passed="0" failed="0" skipped="3">
  <reporter-output>
  </reporter-output>
  <suite started-at="2020-03-18T12:12:04Z" name="Default suite" finished-at="2020-03-18T12:12:04Z" duration-ms="63">
    <groups>
    </groups>
    <test started-at="2020-03-18T12:12:04Z" name="Default test" finished-at="2020-03-18T12:12:04Z" duration-ms="63">
      <class name="testNgEx.BeforeAfterClass">
        <test-method is-config="true" signature="login()[pri:0, instance:testNgEx.BeforeAfterClass@188715b5]" started-at="2020-03-18T08:12:04Z" name="login" finished-at="2020-03-18T08:12:04Z" duration-ms="0" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at testNgEx.BeforeAfterClass.login(BeforeAfterClass.java:33)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:178)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method signature="a1()[pri:0, instance:testNgEx.BeforeAfterClass@188715b5]" started-at="2020-03-18T08:12:04Z" name="a1" finished-at="2020-03-18T08:12:04Z" duration-ms="15" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- a1 -->
        <test-method signature="a2()[pri:0, instance:testNgEx.BeforeAfterClass@188715b5]" started-at="2020-03-18T08:12:04Z" name="a2" finished-at="2020-03-18T08:12:04Z" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- a2 -->
        <test-method signature="a3()[pri:0, instance:testNgEx.BeforeAfterClass@188715b5]" started-at="2020-03-18T08:12:04Z" name="a3" finished-at="2020-03-18T08:12:04Z" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- a3 -->
        <test-method is-config="true" signature="logout()[pri:0, instance:testNgEx.BeforeAfterClass@188715b5]" started-at="2020-03-18T08:12:04Z" name="logout" finished-at="2020-03-18T08:12:04Z" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logout -->
      </class> <!-- testNgEx.BeforeAfterClass -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
